version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running pre-build phase...
      - python -m pytest tests --collect-only  
  build:
    commands:
      - echo Build started on `date`
      - python setup.py install  
  post_build:
    commands:
      - echo Running post-build phase...
      - python -m pytest tests 
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*
